### ISSUE TITLE
`Laracasts\Behat` extension file or class could not be located.  

### ISSUE THREAD

**Issue by dancourse** [laracasts/Behat-Laravel-Extension-Example-App#1]
Hello,

I may be missing something, but on a totally fresh clone of this repo, then running `composer install` and `composer update` (mac, OSX yosemite running in homestead) 

I get 

```
  [Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]  
  `Laracasts\Behat` extension file or class could not be located.               
```

Any help would be great, only I'm having a right ol' mare getting Laravel 5 and Behat 3 to work!

Thanks, DanC

**Comment by nWidart** [comment]
Getting same error here.

**Comment by jesseobrien** [comment]
Ditto. Any progress on this gentlemen?

**Comment by jesseobrien** [comment]
Leaving a potential solution:

If you're using the `global` behat command, it autoloads relative to the global installed version of behat. To get it loading properly, it has to use the local installed version in `./vendor/bin`

**Comment by jaceju** [comment]
Here is my solution:

Update the `behat.yml`:

``` yaml
default:
    extensions:
        Laracasts\Behat\ServiceContainer\LaravelExtension:
            env_path: .env.behat
        Behat\MinkExtension\ServiceContainer\MinkExtension:
            default_session: laravel
            base_url: http://localhost:8000
            laravel: ~
```

Run behat from vendor:

```
$ ./vendor/bin/behat
```
