### ISSUE TITLE
Set "show_cmd" parameter in behat.yml to be able to open page in browser (ex.: "show_cmd: firefox %s") (RuntimeException)

### ISSUE THREAD

**Issue by bizmate** [laracasts/Behat-Laravel-Extension-Example-App#2]
I am experiencing something strange in my experience. Usually behat works straight out the box with browserkit but I have run this example and if I run 

```
Scenario:  Summary page displaying correctly                                                                                                              # features/example.feature:6
    Given I am on the homepage                                                                                                                                     # FeatureContext::iAmOnHomepage()
    Then show last response                                                                                                                                        # FeatureContext::showLastResponse()
      Set "show_cmd" parameter in behat.yml to be able to open page in browser (ex.: "show_cmd: firefox %s") (RuntimeException)
    Then I should see "Activity Summary"
```

Just to show it in bold the error displayed is
*\* Set "show_cmd" parameter in behat.yml to be able to open page in browser (ex.: "show_cmd: firefox %s") (RuntimeException)**

My behat.yml

```
default:
  extensions:
    Laracasts\Behat: ~
    #  env_path: .env.behat
    Behat\MinkExtension\ServiceContainer\MinkExtension:
      default_session: laravel
      base_url: 'http://localhost'
      laravel: ~ 

```

my .env.behat exists **APP_ENV=acceptance**

Any suggestions?

**Comment by BaluErtl** [comment]
Hi @bizmate,

This is the content of my `behat.local.yaml` file used on macOS system:

```yaml
default:
  extensions:
    Behat\MinkExtension:
      base_url: 'http://localhost'
      sessions:
        default:
          goutte: ~
        browserChrome:
          chrome:
            api_url: 'http://chromium:9222'
#     show_cmd: '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome %s'
      show_cmd: '/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser %s'
  formatters:
    tap: false
    pretty:
      output_path: 'php://stdout'
```

On *NIX systems you may want to try using `'firefox %s'` as Behat's error message suggests.
